// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xznjigrpdxtcsfqryxse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6bmppZ3JwZHh0Y3NmcXJ5eHNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4OTAyNjYsImV4cCI6MjA1MjQ2NjI2Nn0.1O7PlOvcg9Jj21m4qga3Y7mGjnLYwFJlm1c7aXK-ul8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);